replicaCount: 2

imageName: lemonpro/weathermate
imageTag: latest
imagePullPolicy: Always

containerPort: 8080

contextPath: "/"

ingress:
  host: weathermateplus.com
  wwwhost: www.weathermateplus.com
  tls:
    - hosts:
        - weathermateplus.com
        - www.weathermateplus.com
      secretName: weathermateplus-com

configs:
  HOST: "https://weathermateplus.com"
  PORT: "8080"

resources:
  limits:
    cpu: "400m"
    memory: "800Mi"
  requests:
    cpu: "300m"
    memory: "800Mi"

startupFailureThreshold: 10
livenessFailureThreshold: 10
readinessFailureThreshold: 10
