apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: production
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.wwwhost }}
      http:
        paths:
          - path: {{ .Values.contextPath }}
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.containerPort }}
            pathType: Prefix
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.contextPath }}
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.containerPort }}
            pathType: Prefix
  tls:
  {{- toYaml .Values.ingress.tls | nindent 4 }}