apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    GOOGLE_API_KEY: AgAzSSgokU4xSqvbIGVFL5ELdkETPpyHARKWD2x+5AGXblHwBerEwXkYzPv7yo8Q9RDVFdxwAqbP7ohK5Fqw+hQCWAVZ3lOZG4yEsNLUiZTapwDANn476Q2o9x8GFvBQrbdhaAu5LYBQVZvKy5xX9vcMAk7Owpuis5yJI0BAHT1doZm2CgFsid0uFJM2l5QOOfuiRIDn/Fy0e3JJLpvqq5fVkBDCgxtuhNyqGLzWJQdDpyMuP02MwIENbD0xrxtWAVmCrfI4/4Yjq6nGq9VpnqB340dCs0arqnG315XDJELhjf0ff7XY2id7kLhtar3CsVhpynQNtu5PjWnaEDN3fizxXxUc746I1u8WRAvD+E47DBbRlbDHEcK1st2MrKNCUO8RlvTCms+K4a81ZYc6flR9Dp3h7ZSS0RAuhBsF6fYVoJ0BTM2xIbvnAoalG0yUl1cJ+IhOplDKjkjoqY0iUUlafV87Gpeni0d/uFjrd3hlN22/NCdz6mvzcN5eo2pVnruRiLRj7ec5HYsGvzUlmrkKCaLw1TF8Ylbzsjk3NjV/IZ2fwxoLF+q5inqsCdUgTnpho2yD+PmJMbK/xFIdyu7zHxp3dK8kbj/CxR9KpLGfjrfFb0KzMjzgVQLvAxtXVn0pt/U1391TCGFGP3utoqNrNNlzOdNu5Dik17xj92y17ZBVOrmXW2CcD8NXwwKX5VxwofLr2MJ13/a5VOpnaoK27uy+/goUpBLPuSjdGTk0j11CO/L1cIs=
  template:
    metadata:
      name: {{ .Chart.Name }}
      namespace: {{ .Release.Namespace }}
