name: api-build

on:
  push:
    branches:
      - main

jobs:
  build-and-push-2-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Container Registry
        run: echo $DOCKER_HUB_TOKEN | docker login -u lemonpro --password-stdin
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and containerize application
        run: |
          docker build -t weathermate:1.0.0-SNAPSHOT .
      - name: Tag & push to DockerHub Registry
        run: |
          docker tag weathermate:1.0.0-SNAPSHOT index.docker.io/lemonpro/weathermate:latest
          docker push index.docker.io/lemonpro/weathermate:latest
      - name: deploy weathermateplus api
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /home/app
            docker-compose pull
            docker-compose down && docker-compose up -d
            echo 'deployment successful'